openapi: 3.0.0
info:
  title: Quiz App API
  version: 1.0.0
  description: API documentation for the Quiz App backend

servers:
  - url: http://localhost:5000

paths:
  /api/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
                  enum: [Admin, User]
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad request

  /api/auth/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
        '400':
          description: Invalid credentials

  /api/quizzes:
    get:
      summary: Get all quizzes
      responses:
        '200':
          description: List of quizzes

  /api/quizzes:
    post:
      summary: Create a new quiz (Admin only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
                questions:
                  type: array
                  items:
                    type: object
                    properties:
                      questionText:
                        type: string
                      options:
                        type: array
                        items:
                          type: string
                      correctAnswer:
                        type: integer
      responses:
        '201':
          description: Quiz created

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT